### ISSUE TITLE
OpenSSL on Windows

### ISSUE THREAD

**Issue by isaacadams** [fennelLabs/fennel-lib#1]
tried adding [openssl](https://docs.rs/openssl/0.10.29/openssl/) as a cargo dependency and it failed on windows -- some extra dependencies need to be installed

# Method 1: use chocolately
Using chocolately, [openssl](https://community.chocolatey.org/packages/openssl) will be installed

open command prompt **in admin mode**
```bash
choco install openssl
```

the installation directory will be: `C:\Program Files\OpenSSL-Win64`

In order for rust to register that openssl has been installed, it needs the OPENSSL_DIR environment variable set
```
set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
echo %OPENSSL_DIR% #compare to expected value
```

# Method 2: Install [vcpkg](https://github.com/microsoft/vcpkg)
run the following
```bash
cd C:\
git clone https://github.com/microsoft/vcpkg
cd vcpkg
bootstrap-vcpkg.bat
vcpkg install openssl::x64-windows
```

the installation directory will be: `C:\vcpkg\packages\openssl_x64-windows`

In order for rust to register that openssl has been installed, it needs the OPENSSL_DIR environment variable set
```
set OPENSSL_DIR=C:\vcpkg\packages\openssl_x64-windows
echo %OPENSSL_DIR% #compare to expected value
```

#### Failure: Dependency does not install during `vcpkg install openssl::x64-windows`
![image](https://user-images.githubusercontent.com/26559009/152467406-812aa488-ade3-4daa-aafb-40027558d01e.png)
- to fix this, I grabbed the http link to the zip file it was complaining about (in this case: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip) 
- move that zip file into `C:\vcpkg\downloads` (or where ever you cloned the repo) 
- once the zip file placed in the `VCPKG_REPO_ROOT\downloads` path, run `vcpkg install openssl::x64-windows`

**Comment by Romulus10** [comment]
We'll probably also need to cover these dependencies on macOS and Linux, honestly. Should be easy though, apt and brew make that job easier.

**Comment by isaacadams** [comment]
> We'll probably also need to cover these dependencies on macOS and Linux, honestly. Should be easy though, apt and brew make that job easier.

you are exactly right, in fact, the openssl crate has the commands for how to install it on macOS, linux, etc. [here](https://docs.rs/openssl/0.10.29/openssl/#automatic)
