### ISSUE TITLE
Fully Tie fennel module to Database

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/fennel-lib#19]
we need to be able to download identities/public keys from Fennel Protocol and insert them into the database.

**Comment by PhillyWebGuy** [comment]
@Romulus10 Are we fetching ALL identities/public keys and inserting them? Or one particular identity?

**Comment by Romulus10** [comment]
Having both as an option would be great.

**Comment by PhillyWebGuy** [comment]
@Romulus10 How do the database/database files (ex: identity.db) come into being/get generated?

**Comment by Romulus10** [comment]
If you run the unit tests, or start up the client/server, they're generated during setup. They can be safely deleted as well, it just creates a whole new server state.

**Comment by PhillyWebGuy** [comment]
@Romulus10 Is there a reason I don't see fennel mod exported here: 

https://github.com/fennelLabs/fennel-lib/blob/ecb6d15217f817588ffd2146a82e3d4693e2203e/src/lib.rs#L11

**Comment by PhillyWebGuy** [comment]
I'm asking because I imagine I'll have to make use of this:

https://github.com/fennelLabs/fennel-lib/blob/ecb6d15217f817588ffd2146a82e3d4693e2203e/src/fennel/mod.rs#L153

**Comment by Romulus10** [comment]
Yeah, we just didn't expose it during the last phase. We got it testing and running, pending some adjustments (which you just pointed out).

**Comment by PhillyWebGuy** [comment]
Ok, I'm going to expose it, push up to a branch, then reference the branch in the Cargo.toml file for the cli.

**Comment by PhillyWebGuy** [comment]
@Romulus10 Any idea how long I should expect generate_keypair to take to execute normally?

https://github.com/fennelLabs/fennel-cli/blob/a4872bbbe52091ebebbd7d62621e336cd2ec3c7f/src/client/mod.rs#L204

**Comment by Romulus10** [comment]
It's very slow as a side-effect of the RSA key generation process. I've had it run half an hour for the 8096-bit generation depending on the machine it's running on.

**Comment by PhillyWebGuy** [comment]
Oh, ok, that's actually good to know. It is just slow, and not something else going on.

**Comment by Romulus10** [comment]
Yep, and the generation function is pretty much _just_ running the RSA keygen algorithm. Not much else happening there. The relative difficulty of the generation algorithm is part of what makes RSA secure.

**Comment by PhillyWebGuy** [comment]
Yeah, for sure. I should have suspected as much as soon as my fan cranked up.

**Comment by PhillyWebGuy** [comment]
@Romulus10 Is it safe to assume that in order to return keys from fetch_public_keys I will first have to insert some? There probably aren't any in the node by default, right?

**Comment by Romulus10** [comment]
Yeah, there won't be any by default.

**Comment by PhillyWebGuy** [comment]
All right, I gotta crash. But this is where I'm leaving off.

I run this:

`fennel-cli create-identity 4294967111`

I get this from the cli:

```
sent
Error: Custom { kind: UnexpectedEof, error: "early eof" }
```

And then this in the terminal window for the server:

```
begin handling new connection
received a packet
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `FennelServerPacket::message_type`" }', src/server/mod.rs:22:86
```
The line of code referenced:

`let server_packet: FennelServerPacket = Decode::decode(&mut (buffer.as_slice())).unwrap();`

I'll pick up there tomorrow.

**Comment by Romulus10** [comment]
Make sure you pull from the most recent main branch for cli and server, then run `cargo update`. It's possible my changes threw you off a bit.
