### ISSUE TITLE
Add a "Message Type" marker to `Message` struct

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/fennel-lib#20]

**Comment by PhillyWebGuy** [comment]
@Romulus10 I'm getting this now on an insert: 

```
received a packet
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "**Could not decode `FennelServerPacket::message_type**`" }', src/server/mod.rs:22:86
```

Am I missing an update somewhere?

**Comment by Romulus10** [comment]
Try pulling from the main branch, running cargo update again, then deleting the message database directory. It's possible you're reading old message data that doesn't have the message_type field.
